name: deploy_docs
on:
  push:
    branches:
      - 'master'
    paths:
      - docs/**
      - README.md
      - mkdocs.yml
      - catflow/**
      - .github/workflows/deploy_docs.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.6.1'
      - run: poetry install --no-interaction --without test
      - run: poetry run mkdocs gh-deploy --force