name: deploy_docs
on:
  push:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
              mkdocs-material \
              mike \
              mkdocstrings[python] \
              mkdocs-gen-files \
              mkdocs-literate-nav \
              mkdocs-section-index
      - run: mkdocs gh-deploy --force